version: 2.1
executors:
  feza-executor:
    docker:
      - image: cimg/base:stable
      
jobs:
  publish-feza:

    executor: feza-executor
    steps:
      - checkout
      - run: |
          # echo Hello, World!

workflows:
  feza-workflow:
    jobs:
      - publish-feza