version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
      
jobs:
  publish-feza:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          # echo Hello, World!

workflows:
  my-custom-workflow:
    jobs:
      - publish-feza